DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR (32) NOT NULL,
   EMAIL VARCHAR (32) NOT NULL,
   COMMENT VARCHAR (32) NOT NULL,
   PRIMARY KEY (ID)
);
INSERT INTO COMMENTS VALUES (NULL, "Kent Austin", "ken@ticats.ca", "Tiger-Cats rule!");
DROP TABLE IF EXISTS IMPORTANTUSERS;
CREATE TABLE IMPORTANTUSERS (
   ID INT NOT NULL AUTO_INCREMENT,
   USERNAME VARCHAR (32) NOT NULL,
   PASSWORD VARCHAR (32) NOT NULL,
   PRIMARY KEY (ID)
);
INSERT INTO IMPORTANTUSERS VALUES (NULL, "Moe", "test123");
INSERT INTO IMPORTANTUSERS VALUES (NULL, "Larry", "secret");
INSERT INTO IMPORTANTUSERS VALUES (NULL, "Curly", "scruffles");
